### ISSUE TITLE
ESPHome 2025.2 deprecated `custom_component`

### ISSUE THREAD

**Issue by narenarora** [deatondg/Switchmate-ESPHome#7]
Hello,

Back after a couple years!
Looks like in the recent versions, ESPHome has deprecated the use of `custom_component` and wants `external_component` to be used instead.

I tried working with ChatGPT for a while, but wasn't able to figure out how to fix the ESPHome yaml for the newer versions. 
Any help here would be great!

```
The "custom" component has been removed. Consider conversion to an external component.
https://esphome.io/guides/contributing#a-note-about-custom-components
```

https://esphome.io/components/external_components#example-of-local-components

Because the below portion is now no longer valid, the rest of the code doesn't work either
```yaml
custom_component:
- lambda: |-
    return {
      new SwitchmateController("Lights (Controller)", false, 2000, dining_light_esp)
    };
  components:
  - id: lights_controller
```
